services:
  frontend:
    build: ./apps/frontend
    networks:
      - internal
      - reverse_proxy
    expose:
      - "80"
    restart: unless-stopped
    container_name: frontend
  
  rest_api:
    build: ./apps/rest-api
    environment:
      - MONGOURI=mongodb://neurocoach-mongo:27017/fitness_ai
      - DATABASE_URL=postgres://postgres:postgres@fitness-ai-db:5432/fitness_ai?sslmode=disable
      - OPENROUTER_KEY=${OPENROUTER_KEY}
      - PORT=80
    depends_on:
      - mongo
      - postgres
    networks:
      - internal
      - reverse_proxy
    expose:
      - "80"
    restart: unless-stopped
    container_name: rest-api
  
  ws_api:
    build: ./apps/ws-api
    networks:
      - internal
      - reverse_proxy
    expose:
      - "80"
    restart: unless-stopped
    container_name: ws-api

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=fitness_ai
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - internal
    restart: unless-stopped
    container_name: fitness-ai-db
  
  mongo:
    image: mongo:4.4
    environment:
      - MONGO_INITDB_DATABASE=fitness_ai
    volumes:
      - mongo_data:/data/db
    networks:
      - internal
    restart: unless-stopped
    container_name: neurocoach-mongo

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      - frontend
      - rest_api
      - ws_api
    networks:
      - reverse_proxy
      - internal
    restart: unless-stopped
    container_name: nginx

volumes:
  postgres_data:
  mongo_data:

networks:
  internal:
    internal: true
  reverse_proxy:
    driver: bridge