name: Test Android App

on:
  pull_request:
    branches:
      - main
    paths:
      - 'apps/android-app/**'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.1'
      
      - name: Install dependencies
        working-directory: apps/android-app/
        run: flutter pub get
      
      - name: Run tests
        working-directory: apps/android-app/
        run: flutter test